version: '3'
services:

  bifrost-gateway:
    build: ./src/Gateways/Bifrost
    container_name: bifrost
    image: mjolnir/bifrost
    ports:
      - "8080:80"
    depends_on:
      - asgard-api

  asgard-api:
    build: ./src/Services/Asgard
    container_name: asgard
    image: mjolnir/asgard
    environment:
      - Heimdall__Secret=${HEIMDALL_SECRET}
    expose:
      - "80"
